//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class SetArmedRequest : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/SetArmed";
        public override string RosMessageName => k_RosMessageName;

        public bool armed;

        public SetArmedRequest()
        {
            this.armed = false;
        }

        public SetArmedRequest(bool armed)
        {
            this.armed = armed;
        }

        public static SetArmedRequest Deserialize(MessageDeserializer deserializer) => new SetArmedRequest(deserializer);

        private SetArmedRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.armed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.armed);
        }

        public override string ToString()
        {
            return "SetArmedRequest: " +
            "\narmed: " + armed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
