//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class SetExternalControlRequest : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/SetExternalControl";
        public override string RosMessageName => k_RosMessageName;

        public bool enabled;

        public SetExternalControlRequest()
        {
            this.enabled = false;
        }

        public SetExternalControlRequest(bool enabled)
        {
            this.enabled = enabled;
        }

        public static SetExternalControlRequest Deserialize(MessageDeserializer deserializer) => new SetExternalControlRequest(deserializer);

        private SetExternalControlRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enabled);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enabled);
        }

        public override string ToString()
        {
            return "SetExternalControlRequest: " +
            "\nenabled: " + enabled.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
