//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class EspStateMsg : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/EspState";
        public override string RosMessageName => k_RosMessageName;

        //  Telemetry from the Tardigrade ESP32 flight controller.
        //  Mirrors the State (0x80) frame in the firmware wire protocol
        //  (tardigrade_firmware: firmware/include/comms/Protocol.h). Republished by the
        //  esp_bridge node so Foxglove and rosbag can see and record ESP-side state.
        public BuiltinInterfaces.TimeMsg stamp;
        //  ROS receive time on the Jetson, not the ESP clock
        public float roll;
        //  rad
        public float pitch;
        //  rad
        public float yaw;
        //  rad
        public float depth;
        //  m, ENU z (VehicleState.altitude_m; negative = deeper)
        public float vertical_velocity;
        //  m/s, + is up
        public bool armed;
        public bool state_valid;
        //  attitude estimate is trustworthy
        public bool altitude_valid;
        //  depth/vertical channel specifically
        public bool link_ok;
        //  operator command link is fresh
        public bool pose_ok;
        //  Jetson pose link is fresh (robosub)

        public EspStateMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.roll = 0.0f;
            this.pitch = 0.0f;
            this.yaw = 0.0f;
            this.depth = 0.0f;
            this.vertical_velocity = 0.0f;
            this.armed = false;
            this.state_valid = false;
            this.altitude_valid = false;
            this.link_ok = false;
            this.pose_ok = false;
        }

        public EspStateMsg(BuiltinInterfaces.TimeMsg stamp, float roll, float pitch, float yaw, float depth, float vertical_velocity, bool armed, bool state_valid, bool altitude_valid, bool link_ok, bool pose_ok)
        {
            this.stamp = stamp;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
            this.depth = depth;
            this.vertical_velocity = vertical_velocity;
            this.armed = armed;
            this.state_valid = state_valid;
            this.altitude_valid = altitude_valid;
            this.link_ok = link_ok;
            this.pose_ok = pose_ok;
        }

        public static EspStateMsg Deserialize(MessageDeserializer deserializer) => new EspStateMsg(deserializer);

        private EspStateMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.depth);
            deserializer.Read(out this.vertical_velocity);
            deserializer.Read(out this.armed);
            deserializer.Read(out this.state_valid);
            deserializer.Read(out this.altitude_valid);
            deserializer.Read(out this.link_ok);
            deserializer.Read(out this.pose_ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
            serializer.Write(this.depth);
            serializer.Write(this.vertical_velocity);
            serializer.Write(this.armed);
            serializer.Write(this.state_valid);
            serializer.Write(this.altitude_valid);
            serializer.Write(this.link_ok);
            serializer.Write(this.pose_ok);
        }

        public override string ToString()
        {
            return "EspStateMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\ndepth: " + depth.ToString() +
            "\nvertical_velocity: " + vertical_velocity.ToString() +
            "\narmed: " + armed.ToString() +
            "\nstate_valid: " + state_valid.ToString() +
            "\naltitude_valid: " + altitude_valid.ToString() +
            "\nlink_ok: " + link_ok.ToString() +
            "\npose_ok: " + pose_ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
