//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class GateDetectionMsg : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/GateDetection";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public bool visible;
        public float confidence;
        //  Image-space target center. Use normalized image coordinates in [0, 1].
        public float center_x;
        public float center_y;
        //  Robot-relative target estimate. Positive yaw means target is to robot-left.
        public float yaw_error_rad;
        public float pitch_error_rad;
        public float distance_m;
        //  Competition-side labels. Leave false when unknown.
        public bool survey_and_repair_visible;
        public bool search_and_rescue_visible;
        public string recommended_side;

        public GateDetectionMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.visible = false;
            this.confidence = 0.0f;
            this.center_x = 0.0f;
            this.center_y = 0.0f;
            this.yaw_error_rad = 0.0f;
            this.pitch_error_rad = 0.0f;
            this.distance_m = 0.0f;
            this.survey_and_repair_visible = false;
            this.search_and_rescue_visible = false;
            this.recommended_side = "";
        }

        public GateDetectionMsg(BuiltinInterfaces.TimeMsg stamp, bool visible, float confidence, float center_x, float center_y, float yaw_error_rad, float pitch_error_rad, float distance_m, bool survey_and_repair_visible, bool search_and_rescue_visible, string recommended_side)
        {
            this.stamp = stamp;
            this.visible = visible;
            this.confidence = confidence;
            this.center_x = center_x;
            this.center_y = center_y;
            this.yaw_error_rad = yaw_error_rad;
            this.pitch_error_rad = pitch_error_rad;
            this.distance_m = distance_m;
            this.survey_and_repair_visible = survey_and_repair_visible;
            this.search_and_rescue_visible = search_and_rescue_visible;
            this.recommended_side = recommended_side;
        }

        public static GateDetectionMsg Deserialize(MessageDeserializer deserializer) => new GateDetectionMsg(deserializer);

        private GateDetectionMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.visible);
            deserializer.Read(out this.confidence);
            deserializer.Read(out this.center_x);
            deserializer.Read(out this.center_y);
            deserializer.Read(out this.yaw_error_rad);
            deserializer.Read(out this.pitch_error_rad);
            deserializer.Read(out this.distance_m);
            deserializer.Read(out this.survey_and_repair_visible);
            deserializer.Read(out this.search_and_rescue_visible);
            deserializer.Read(out this.recommended_side);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.visible);
            serializer.Write(this.confidence);
            serializer.Write(this.center_x);
            serializer.Write(this.center_y);
            serializer.Write(this.yaw_error_rad);
            serializer.Write(this.pitch_error_rad);
            serializer.Write(this.distance_m);
            serializer.Write(this.survey_and_repair_visible);
            serializer.Write(this.search_and_rescue_visible);
            serializer.Write(this.recommended_side);
        }

        public override string ToString()
        {
            return "GateDetectionMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nvisible: " + visible.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ncenter_x: " + center_x.ToString() +
            "\ncenter_y: " + center_y.ToString() +
            "\nyaw_error_rad: " + yaw_error_rad.ToString() +
            "\npitch_error_rad: " + pitch_error_rad.ToString() +
            "\ndistance_m: " + distance_m.ToString() +
            "\nsurvey_and_repair_visible: " + survey_and_repair_visible.ToString() +
            "\nsearch_and_rescue_visible: " + search_and_rescue_visible.ToString() +
            "\nrecommended_side: " + recommended_side.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
