//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class RobotStatusMsg : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/RobotStatus";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public bool control_connected;
        public bool armed;
        public bool external_control_enabled;
        public byte nav_state;
        public byte arming_state;
        public string detail;

        public RobotStatusMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.control_connected = false;
            this.armed = false;
            this.external_control_enabled = false;
            this.nav_state = 0;
            this.arming_state = 0;
            this.detail = "";
        }

        public RobotStatusMsg(BuiltinInterfaces.TimeMsg stamp, bool control_connected, bool armed, bool external_control_enabled, byte nav_state, byte arming_state, string detail)
        {
            this.stamp = stamp;
            this.control_connected = control_connected;
            this.armed = armed;
            this.external_control_enabled = external_control_enabled;
            this.nav_state = nav_state;
            this.arming_state = arming_state;
            this.detail = detail;
        }

        public static RobotStatusMsg Deserialize(MessageDeserializer deserializer) => new RobotStatusMsg(deserializer);

        private RobotStatusMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.control_connected);
            deserializer.Read(out this.armed);
            deserializer.Read(out this.external_control_enabled);
            deserializer.Read(out this.nav_state);
            deserializer.Read(out this.arming_state);
            deserializer.Read(out this.detail);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.control_connected);
            serializer.Write(this.armed);
            serializer.Write(this.external_control_enabled);
            serializer.Write(this.nav_state);
            serializer.Write(this.arming_state);
            serializer.Write(this.detail);
        }

        public override string ToString()
        {
            return "RobotStatusMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\ncontrol_connected: " + control_connected.ToString() +
            "\narmed: " + armed.ToString() +
            "\nexternal_control_enabled: " + external_control_enabled.ToString() +
            "\nnav_state: " + nav_state.ToString() +
            "\narming_state: " + arming_state.ToString() +
            "\ndetail: " + detail.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
