//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TardigradeInterfaces
{
    [Serializable]
    public class SlalomMarkerDetectionMsg : Message
    {
        public const string k_RosMessageName = "tardigrade_interfaces/SlalomMarkerDetection";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public byte marker_index;
        public bool visible;
        public float confidence;
        //  Image-space target center. Use normalized image coordinates in [0, 1].
        public float center_x;
        public float center_y;
        //  Robot-relative target estimate. Positive yaw means target is to robot-left.
        public float yaw_error_rad;
        public float distance_m;
        //  Alignment target for passing on the marker's left side.
        public float left_side_yaw_error_rad;
        public float left_side_lateral_offset_m;

        public SlalomMarkerDetectionMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.marker_index = 0;
            this.visible = false;
            this.confidence = 0.0f;
            this.center_x = 0.0f;
            this.center_y = 0.0f;
            this.yaw_error_rad = 0.0f;
            this.distance_m = 0.0f;
            this.left_side_yaw_error_rad = 0.0f;
            this.left_side_lateral_offset_m = 0.0f;
        }

        public SlalomMarkerDetectionMsg(BuiltinInterfaces.TimeMsg stamp, byte marker_index, bool visible, float confidence, float center_x, float center_y, float yaw_error_rad, float distance_m, float left_side_yaw_error_rad, float left_side_lateral_offset_m)
        {
            this.stamp = stamp;
            this.marker_index = marker_index;
            this.visible = visible;
            this.confidence = confidence;
            this.center_x = center_x;
            this.center_y = center_y;
            this.yaw_error_rad = yaw_error_rad;
            this.distance_m = distance_m;
            this.left_side_yaw_error_rad = left_side_yaw_error_rad;
            this.left_side_lateral_offset_m = left_side_lateral_offset_m;
        }

        public static SlalomMarkerDetectionMsg Deserialize(MessageDeserializer deserializer) => new SlalomMarkerDetectionMsg(deserializer);

        private SlalomMarkerDetectionMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.marker_index);
            deserializer.Read(out this.visible);
            deserializer.Read(out this.confidence);
            deserializer.Read(out this.center_x);
            deserializer.Read(out this.center_y);
            deserializer.Read(out this.yaw_error_rad);
            deserializer.Read(out this.distance_m);
            deserializer.Read(out this.left_side_yaw_error_rad);
            deserializer.Read(out this.left_side_lateral_offset_m);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.marker_index);
            serializer.Write(this.visible);
            serializer.Write(this.confidence);
            serializer.Write(this.center_x);
            serializer.Write(this.center_y);
            serializer.Write(this.yaw_error_rad);
            serializer.Write(this.distance_m);
            serializer.Write(this.left_side_yaw_error_rad);
            serializer.Write(this.left_side_lateral_offset_m);
        }

        public override string ToString()
        {
            return "SlalomMarkerDetectionMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nmarker_index: " + marker_index.ToString() +
            "\nvisible: " + visible.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ncenter_x: " + center_x.ToString() +
            "\ncenter_y: " + center_y.ToString() +
            "\nyaw_error_rad: " + yaw_error_rad.ToString() +
            "\ndistance_m: " + distance_m.ToString() +
            "\nleft_side_yaw_error_rad: " + left_side_yaw_error_rad.ToString() +
            "\nleft_side_lateral_offset_m: " + left_side_lateral_offset_m.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
